name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.12-buster

    services:
      db:
        image: postgres:16.1-alpine
        env:
          POSTGRES_DB: wishlist
          POSTGRES_USER: wishlist
          POSTGRES_PASSWORD: wishlist

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.7.1

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint
